#remote_theme: jekyll-theme-minimal-mistakes 
title: Sahil Pawar
logo: logo123.png
# description: FO @CambridgeWealth. BSc Economics from Gokhale Institute 
show_downloads: false
show_github: false
theme: jekyll-theme-minimal
email: "mailto:1sahilpawar@gmail.com"
favicon: true
blank_title: false 
color-scheme: light
