#remote_theme: jekyll-theme-minimal-mistakes
title: Sahil Pawar
logo: /assets/img/headshot_circle.png
description: FO @CambridgeWealth. BSc Economics from Gokhale Institute 
show_downloads: false
theme: jekyll-theme-minimal
